quarkus:
  http:
    host: 0.0.0.0
    port: 8080
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:./output/myDb
  hibernate-orm:
    log:
      sql: true
    database:
      generation: update